### PR TITLE
Update png2c.py to be PROGMEM-compatible

### PR DESCRIPTION
**Pull request by progmem**
png2c.py was created after the work I did to convert the original bin2c.py back in PR #2. Because of this, png2c.py doesn't have the necessary change to make it store the image in program memory; this pull request works to resolve that.

### CODE REVIEW

**Comment by LightningStalker** [comment]
Closed duplicate pull request

**Comment by progmem** [comment]
Looks like we both had the same idea at once, lol

**Comment by shinyquagsire23** [comment]
LGTM

**Comment by LightningStalker** [comment]
How are you guys debugging this?  I have tried simavr, but am running into some dead ends.  There has to be a better way than just making modifications, plugging it in and seeing what happens.

**Comment by progmem** [comment]
Personally, my preferred method is 'flash onto a development board and test', with the occasional use of a hardware debugger or logic analyzer for more complex projects.

For a project like this, which uses LUFA to handle the USB portion, I'm not as concerned about what's coming over the cable as I am the processes that are written to act/respond in a given window. Many times that can be the result of multiple iterations through something, rather than small tweaks.

In the case of png2c.py and bin2c.py, I had some prior experience working with program memory, so it was simply a matter of finding where I can apply those concepts in this fork. That prior knowledge and experience, well, that may've had a couple of attempts flashing a board and scratching my head.

**Comment by LightningStalker** [comment]
Ok thanks

**Pull request merged**
