### PR TITLE
Add LED and buzzer functionality

### PR DESCRIPTION
**Pull request by LightningStalker**
Onboard LED(s) flash and buzzer sounds (optional) after printing to notify the user it's time to review and post the image.

Update README with LED information, instructions for attaching the optional buzzer, build and flash instructions for Arduino Micro, and grammatical tuning

### CODE REVIEW

**Comment by shinyquagsire23** [comment]
Hm, I'm a little uneasy throwing HIGHs onto all the pins on those ports, it might be worthwhile to `#ifdef` the LED/buzzing functionality and have a Makefile define instead so that it has to be a conscious decision to enable, ie `make -DPRINT_ALERTS` and `#ifdef PRINT_ALERTS ... #endif` or something, not sure what a good name for that would be.

At least for me I'll sometimes have other things soldered to my microcontrollers and using it for something like this is more of a temporary thing.

**Comment by LightningStalker** [comment]
Okay will dew
Can't say I blame you, dev boards are on the expensive side

**Comment by LightningStalker** [comment]
Okay, ready for discussion/approval.

**Comment by LightningStalker** [comment]
As close to perfect as I can get it

**Comment by LightningStalker** [comment]
Thanks for thumb up guys been working hard on this!

**Comment by shinyquagsire23** [comment]
LGTM

**Pull request merged**
