### PR TITLE
Reduce the printing time by a 20% (down to 25 minutes... 30% and 21 minutes with an experimental option)

### PR DESCRIPTION
**Pull request by Retropotenza**
- Refactored the position updates and state management, to simplify the development of new printing patterns
- Added a zig-zag printing pattern that avoid issuing stop commands (well only one every two lines remains)
- We can print a line with 321 commands (vs the previous 640), but now we need to send 5 USB request per command (vs the previous 3), to avoid pixel skipping
- The overall printing time per pixel went down to 40 ms, from 48 ms

### CODE REVIEW

**Comment by Retropotenza** [comment]
In theory this should have gone twice as fast (15 minutes to print), but any setting that goes below 33 ms/pixel (33.333 ms/pixel... corresponds to a 30 fps) seems to create pixel skipping.

Now we are at 40 ms/pixel, with 5 USB reports sent for each printing command (8 ms each).

I tried to go to 33 ms/pixel, setting the USB polling frequency to 11 ms, with 2 echo (3 reports). The device continue to generate a 8 ms polling :-(... Indeed it looks that only multiple of 8 ms polling frequency at the end are generated, whatever setting is tried.

**Comment by Retropotenza** [comment]
I found a way to reach 30 fps (almost) while printing: injecting an additional "echo" USB report (8 ms) every 6 commands (each doing 3 "echo", lasting 4 USB reports and 32 ms). This align the 6 commands to 200 ms, equal to 6 video frames.

I had to change (again) the printing pattern, simplifying the tests in it (the previous one didn't work well in my initial tests). I stripped away all the unnecessary tests, to reduce as much as possible any eventual timing risks.

This "synched" mode is currently enable by default by a #define, but we may leave it disabled (the new printing pattern by itself is safer, and anyways prints in 25 minutes).

**Comment by LightningStalker** [comment]
I was thinking about some ways to further speed up printing. For instance skipping blank lines and counting to see if there are more black pixels than white and if so using a thick pen to color everything black and then the small eraser to print white pixels, types of things a human sketcher would do instinctively

**Comment by Retropotenza** [comment]
The challenge here is to understand how the acceleration triggered by consecutive moves in the same direction works. I initially do some quick test, and was not something trivial to measure.

On a second thought, at that time I didn't yet understood the timing relationships between video refresh and USB reports. If N moves in the same direction generate always a skip on M pixel, a kind of run length encoding printing could be done.

The low hanging fruit is "positive" printing, that could accelerate handmade drawings (but mot much dither images).

**Comment by Retropotenza** [comment]
I did more test, and I found that sometimes the printing pattern breaks, if SYNC_TO_30_FPS is set. Is not just a pixel skew, it completely skew all the USB report stream. I believe that the frequency completely match, but that there is a random offset that in these conditions could generate this issue.
We need an additional stage at the beginning. The idea (if feasible) is to check the time that pass between when the device is ready to send a report, and when the Switch is ready to receive it, and insert some spin loops until they are below a working threshold.

**Comment by Retropotenza** [comment]
I was never able to make the sync the printing to 30 fps... and in Splatoon 3 the zig zag pattern doesn't seems to work anymore. I had to set ECHOES to 3 instead of 2 and to print one line at the time to get a goof result.

I will close this pull request :-)...

**Pull request closed without merging**
