### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 1e1001**
make doesn't work on windows

### CODE REVIEW

**Comment by Alenonimo** [comment]
I found a tutorial somewhere else that have more details: https://gbatemp.net/threads/tutorial-printing-spla2n-posts-with-an-arduino-teensy-board.482166/

The part of that tutorial related to this question is regarding the MinGW program (name basically means minimal GNU for Windows), so installing and setting it up will give you the "make" command and a few others. Alternatively, "make" is also in the Windows Subsystem for Linux if you want to use something more official: https://www.technewstoday.com/install-and-use-make-in-windows/

But yeah, having this on the tutorial would make the project a bit more accessible since most people uses Windows and don't know much about these things.

**Comment by Alenonimo** [comment]
Holy fuck, this took some effort to make it work.

Not only do you need the MinGW program, you also need the AVR-GCC Toolchain from Atmel, but they keep moving the file around quite a lot. The current location for the darn thing is https://www.microchip.com/en-us/tools-resources/develop/microchip-studio/gcc-compilers

I grabbed the Windows version, shoved it somewhere in C:\, edited the %PATH% to include it's bin directory and only then it worked. Also, instead of "make", for MinGW I had to use the "mingw32-make" command. It does the thing.

The site also has the file for the Linux version but I don't know how to make my WSL to get the file or install it. Someone with more linux know-how might appreciate knowing where this file is though, since I couldn't just sudo install the thing.

So there you have it. Grab the LUFA, dump somewhere, grab this repository using Github Desktop, make a fork I guess, dump somewhere, edit the "makefile" to match the chip of the device and to point to where LUFA is, install Python, install the libpng for Python so png2c works, install MinGW, put the bin directory on the path, grab the AVR Toolchain, extract somewhere, put the bin directory on the path and THEN it works. Whew.

Not counting how many times I had to send the device I bought back because they weren't supported (I curse whoever made the UNO with the CH340 USB chip) or lacked the reset button, it just took me a week and half to make the darn thing.

**Comment by 0xLinkz** [comment]
I found the windows way too frustrating and just used an Ubuntu VM on Windows. Has anyone gotten this to work with Splatoon 3? I've been having issues.

**Comment by Retropotenza** [comment]
Splatoon 3 needs a input change and a different timing. I did some test during the last festival, but I still have to try it on the final released game. See my fork in https://github.com/Retropotenza/Switch-Fightstick (it uses Arduino Uno as default, I don't have a Teensy).

**Comment by david6563** [comment]
> make doesn't work on windows

It does, I'm on W11. To get it to work on windows you have to edit your environment variables in your System file paths. Add the bin file paths and restart your terminal. I have a new problem you might run into. I'm getting a "no rule to make target `LUFA/Build...`. I can't seem to solve it.

**Comment by 1e1001** [comment]
Surprised that a >2 year old PR is getting comments all of a sudden! I made it before I knew how to actually compile things, and looking back at it now this change actually seems pretty silly. I imagine you should probably move this discussion to an issue of it's own.

**Comment by CVRRV** [comment]
Working for me right now on Splatoon 3, TY for the fork @Retropotenza !!!

**Pull request closed without merging**
