### PR TITLE
Updates on the printing procedure

### PR DESCRIPTION
**Pull request by Retropotenza**
Now the tool automatically set the position of the cursor at start (it look robust to any eventual pixel skipping, when initially moving from Y -1 to 0 position).

### CODE REVIEW

**Comment by LightningStalker** [comment]
I was working on this for 2 days straight with hardly any success.  Some comments posted in the closed pull request in agreement with what you have found

Edit: NVM, I guess you saw them.  I also discovered that the skipping on the first line was eliminated by allowing it to settle a while after syncing.  It looks like you have all that taken care of.  I will test as soon as I get a chance.

**Comment by LightningStalker** [comment]
OMG THIS FIXES EVERYTHING!!!  Nice work!

**Comment by shinyquagsire23** [comment]
LGTM, code looks way better too.

**Comment by LightningStalker** [comment]
It just finished printing a pixel perfect print of my test image.  
Test Print

**Comment by Retropotenza** [comment]
Thanks 😀. I still saw in one test some skipping. I don't have an USB convert, so 'm only using a dock. How are you using this?

Repeating the last report 10 times, for 100 ms (with `#define ECHO_WAIT_TIME_MS 100` and `#define ECHO_DELAY_MS 10`) avoided this, but it slows down the printing process ☹️.

**Comment by LightningStalker** [comment]
I don't have one either.  The Switch is in the dock and attached to an `APC USB2HUB-7P-1V`.  I am plugging the Teensy into the topmost port on the side where the power connector goes in.

**Comment by 4130** [comment]
I couldn't make it.
Such an error was displayed.

> obj/image.o:(.progmem.data+0x0): multiple definition of `image_data'
> obj/Joystick.o:(.progmem.data+0x0): first defined here

**Comment by Retropotenza** [comment]
Strange... maybe an old .o link issue? Did you make clean before make?

**Comment by 4130** [comment]
I deleted the obj folder containing the .o file and make it again, but I got an error.

I use WinAVR 20100110 4.3.3

**Comment by Retropotenza** [comment]
Maybe I understood... the compiler may be more picky than mine. Try to put an 'extern' before 'const uint8_t image_data[0x12c1] PROGMEM;' in joystick.c.

**Comment by 4130** [comment]
thx
I did it!
And it works well.

**Comment by Retropotenza** [comment]
Good, I added this fix in the last pull request.

**Pull request merged**
