### PR TITLE
Update Joystick.c

### PR DESCRIPTION
**Pull request by LightningStalker**
Hopefully this fixes the entire image being offset one pixel to the left.  This was due to moving left before the first pixel on each line is drawn.  I am really tired right now (was up all night) and cannot test it, but will once I get some much needed sleep.

I'm not sure what the weirdness is going on in the upper left.  It's easy enough to fix by hand, but it would be really interesting to figure out what this is.

Finally, when it gets to the second to last line, it doesn't move down and draws the last line over it.  This I am not entirely sure about either and warrants further investigation because it is not as easy to fix by hand.

### CODE REVIEW

**Comment by shinyquagsire23** [comment]
Yeah let me know what it's looking like, it's been a bit since I've had the chance to really look at it but I do recall the right side was always blank and the left side had some overlap between two columns. I think it has something to do with the timing, maybe pressing down should be done for two samples.

**Comment by Retropotenza** [comment]
Nope, this didn't work for me. The cursor got stuck on the right.

**Comment by LightningStalker** [comment]
Ok forget this one, then.  I have another idea.

**Comment by LightningStalker** [comment]
Ok forget this one, then. I have another idea.

**Comment by LightningStalker** [comment]
Something is causing it to move left before the start of a line, even if `ReportData->HAT = 0x6; //go left` is commented out.  This is so tedious having to plug it into the Switch every time to check after making a change.

**Comment by LightningStalker** [comment]
After some extensive testing, I have come to the conclusion that the right column and bottom row of the drawing window are inherently pushing the cursor away.

Fortunately, I do have a fix for the problem in the upper left and am working on a fix for the left and bottom.  For the bottom it's just going to be throwing out the last line since the aforementioned pushing effect causes it to draw over the top of the previous line and there doesn't seem to be anything that can be done with it while emulating the HORI Pokken Pad in this manner.

**Comment by Retropotenza** [comment]
I've found that the right stick X and Y set to 0, by the memset at the beginning, are pushing the cursor... You may check this adding:

`ReportData->LX = 128;`
`ReportData->LY = 128;`
`ReportData->RX = 128;`
`ReportData->RY = 128;`

Or you can try it with the joy-cons (keeping the right stick in the bottom left you I got the same behaviour of the program).

Anyways... after this tentative fix, on my console I get a column skip at column 4, on all rows... It's strange because also moving step by step with the Joy-con I'm getting the same behaviour.

**Comment by LightningStalker** [comment]
I suspected that, but forgot about RX, thanks!

**Pull request closed without merging**
