### PR TITLE
Tuning on timing, and a fix on double variable declaration

### PR DESCRIPTION
**Pull request by Retropotenza**
With 40 ms of echo wait time you may still see some pixel skipping, expecially when printing lines with some white or black continous areas (not a big issue for dithered images, but still something worth to fix). Is a bit slower :-(.

image_data declared as external (as it should formally be), to improve compiler compatibility.

### CODE REVIEW

**Comment by LightningStalker** [comment]
I suppose if we have to sacrifice some time for accuracy . . .

**Review by LightningStalker — APPROVED** [review]
I suppose if we must sacrifice a little time for accuracy

**Comment by shinyquagsire23** [comment]
Yeah speed vs accuracy seems to be an irritating issue here but I think I'd rather go for accuracy, LGTM

**Comment by LightningStalker** [comment]
Warrants further testing, though, 40 to 60 is a 150% increase in time, possibly there's a sweet spot somewhere in between

**Comment by Retropotenza** [comment]
Well... 50 ms failed one time with the test pattern in the repo... 80 ms was fine, 60 looked OK in 3 consecutive test runs. Anyways I think that the issue is really sporadic, and maybe related to the Switch side, busy in processing something else.

Under the latter hypothesis increasing the time will just increase the probability of sending reports when the Switch is busy :-(.

**Comment by Retropotenza** [comment]
Oh I also tried some other optimizations:

* Keeping the pencil down when moving. This speed up and have a nice sound brush effect, but need tuning in timing... it sound promising since the printing timing per pixel will be constant (now the time per pixel double for black pixels).
* Change the carriage return, to point to X,Y = 0,0 using analogs sticks, and then move down to the right Y with down button (you will need an additional Y global coordinate here).
* Print during carriage return, here I see and issue moving left step by step... the 4th or 5th to last column is skipped (also with the joy-cons).

Next week I'll be at seaside, away from keyboard 🏝, if interested you may try these improvements.

**Comment by LightningStalker** [comment]
That may explain why it seems to drop input sometimes during gameplay. Handshaking or buffering would be nice. Hope you enjoy 🏖

**Pull request merged**
